# SPDX-FileCopyrightText: ASSUME Developers
#
# SPDX-License-Identifier: AGPL-3.0-or-later

services:
  assume_db:
    image: timescale/timescaledb-ha:pg17-oss
    # smaller without postgis support:
    # image: timescale/timescaledb:latest-pg17
    container_name: assume_db
    restart: always
    # running as 0 removes the need to create the volume bind-mount beforehand
    user: "0:0"
    environment:
      - POSTGRES_USER=assume
      - POSTGRES_PASSWORD=assume
      - POSTGRES_DB=assume
      - TS_TUNE_MAX_CONNS=500
      # pgdata is /home/postgres/pgdata otherwise
      # https://github.com/timescale/timescaledb-docker-ha/blob/345ceabef65c808ec6aaaa61a8b6ca568ccad7d3/Dockerfile#L460
      - PGDATA=/var/lib/postgresql/data
    volumes:
      # needed for normal image
      - ./assume-db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  grafana:
    image: grafana/grafana-oss:latest
    container_name: assume_grafana
    user: "104"
    depends_on:
      - assume_db
    ports:
      - 3000:3000
    environment:
      GF_SECURITY_ALLOW_EMBEDDING: "true"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_INSTALL_PLUGINS: "marcusolsson-dynamictext-panel,orchestracities-map-panel"
      GF_SECURITY_ADMIN_USER: assume
      GF_SECURITY_ADMIN_PASSWORD: "assume"
      GF_RENDERING_SERVER_URL: http://renderer:8081/render
      GF_RENDERING_CALLBACK_URL: http://grafana:3000/
      GF_LOG_FILTERS: rendering:debug
      GF_USERS_DEFAULT_THEME: light
    volumes:
      - ./docker_configs/grafana.ini:/etc/grafana/grafana.ini
      - ./docker_configs/datasources:/etc/grafana/provisioning/datasources
      - ./docker_configs/dashboards:/etc/grafana/provisioning/dashboards
      - ./docker_configs/dashboard-definitions:/etc/grafana/provisioning/dashboard-definitions
    restart: always
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints: [node.role == manager]

  pgadmin:
    # user: root
    image: dpage/pgadmin4:latest
    container_name: pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: a@a.a
      PGADMIN_DEFAULT_PASSWORD: a
      PGADMIN_LISTEN_PORT: 80
      PGADMIN_CONFIG_UPGRADE_CHECK_ENABLED: "False"
    # volumes:
    #   - ./data/pgadmin:/var/lib/pgadmin
    ports:
      - "8080:80"
